var userName = "shivam";
var password = "abc@gmail.com";
var userAge = 24;
var salary = 10000.20;
var userDetails = "He is programmer ".concat(userName);
console.log(typeof userName);
console.log(typeof password);
console.log(typeof userAge);
console.log(typeof salary);
console.log(userDetails);
